### ISSUE TITLE
Inconsistency in slurm spec tests?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#10]
In slurm_spec we have this:

```ruby
describe "#submit" do
  def build_script(opts = {})
    OodCore::Job::Script.new(
      {
        content: content
      }.merge opts
    )
  end
  # ...
  subject { adapter.submit(script: build_script) }

  it "returns job id" do
    is_expected.to eq("job.123")
    expect(slurm).to have_received(:submit_string).with(content, args: [], env: {})
  end

  context "with :queue_name" do
    before { adapter.submit(script: build_script(queue_name: "queue")) }

    it { expect(slurm).to have_received(:submit_string).with(content, args: ["-p", "queue"], env: {}) }
  end
```

We specify subject to be the return of the method call `adapter.submit(script: build_script)`. But this subject is only used for one test,  `it "returns job id" do` as what follows are multiple contexts, where the "subject" of the context is actually in the `before`.

Would it be more appropriate for the initial test to work the same way? According to http://betterspecs.org/#subject the user of subject is for multiple tests sharing the same subject, but we don't seem to have that here.

Just trying to understand, see if I'm missing something.

**Comment by nickjer** [comment]
It probably just got carried over from my personal preference where I typically set the subject to the method being tested (it makes remembering what the subject is in tests easier). That and the `let(:slurm)` still keeps the code as DRY a named subject.

But you are right that there is no reason for it to be the subject in this case since majority of tests are on `slurm`. But the only benefit would be reducing the code size slightly from:

```ruby
it { expect(slurm).to have_received(:submit_string).with(content, args: [], env: {}) }
```

to

```ruby
it { is_expected.to have_received(:submit_string).with(content, args: [], env: {}) }
```

But then I'd have to remember that the subject is the `slurm` object.

If we did make this the subject, I would lean towards a named subject so it is more clear what is being tested. But then we wouldn't reap the benefits of the code reduction.

**Comment by ericfranz** [comment]
Will revisit tests later.
