### ISSUE TITLE
Catch exceptions when reading bad cluster yml files

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#150]
We've gotten issues from users of this library (ourselves in the Ondemand dashboard) where exceptions are thrown from reading invalid yml files for cluster configs.

The offending read line is [here](https://github.com/OSC/ood_core/blob/869cd93878c30ae4fc9f469f062b9452d94b61b4/lib/ood_core/clusters.rb#L31) and the solution seems simply to catch (rescue in ruby parlance) the exception, spitting out the relevant message in logs. 
```ruby
          Pathname.glob(config.join("*.yml")).each do |p|
            CONFIG_VERSION.any? do |version|
              if cluster = YAML.safe_load(p.read).fetch(version, nil)
                clusters << Cluster.new(send("parse_#{version}", id: p.basename(".yml").to_s, cluster: cluster))
                true
              else
```

**Comment by ericfranz** [comment]
This library currently has no logger available to it. If #86 were available, that could be used. But the problem with logging and returning an empty array is that it makes it more difficult for the code that uses the library to determine that an error occurred. All the user of this code would know is that there are no clusters available.

I remember when Jeremy first avoided fixing this. His point was that we shouldn't let the app start with a malformed cluster config - we should let it crash so the user immediately knows the problem. Now with the current version of OnDemand, I'm not sure if this error occurs early enough in the launching of the Dashboard app to cause Passenger to display that debug page, and users may still need to fish through logs to determine what happened.

Since this is a library I think there are two approaches preferable to logging an error and returning a Clusters object with a zero length of clusters.

1. rescue specific exceptions, like the `Psych::SyntaxError` or other errors, and re-raise an ood_core specific error
   - similar to [ConfigurationNotFound](https://github.com/OSC/ood_core/blob/869cd93878c30ae4fc9f469f062b9452d94b61b4/lib/ood_core/clusters.rb#L40) this could be a `ConfigurationMalformedError` error or `ConfigurationParsingError`
   - The app itself (Dashboard, ActiveJobs, etc.) can catch these errors and handle them appropriately. In these apps case, that would appear to require a change to how ood_appkit works, because it currently parses the files here https://github.com/OSC/ood_appkit/blob/ea1435d4bbff47cd1786f84096f415441089a7f5/lib/ood_appkit/configuration.rb#L127-L131 and this is lazy loaded after the first call to [OodAppkit.clusters](https://github.com/OSC/ood_appkit/blob/ea1435d4bbff47cd1786f84096f415441089a7f5/lib/ood_appkit/configuration.rb#L17-L19). In the OodAppkit.clusters method we could catch the `ConfigurationParsingError` and set a `OodAppkig.clusters_error_msg` which could be used by the apps.
2. Rescue and create a new `InvalidCluster` instance, a [special case](https://martinfowler.com/eaaCatalog/specialCase.html) Cluster that is invalid, doesn't exist, and contains information about the parsing error. All of the allow methods would return false on this Cluster object of course. The nice thing about this approach is you could get a mixture of valid and invalid Cluster objects, you get the error messages to display in the Dashboard for those broken cluster files, and then valid ones can still be used and work.
   - this option is it actually gets rid of an exceptional case altogether (["define exceptions out of existence"](https://www.amazon.com/exec/obidos/ASIN/1732102201/)). It might be tricky to get the special case right cause its a type of [Null object](https://martinfowler.com/eaaCatalog/specialCase.html) where it still has to have all the values to look like a cluster, and there is one less gem to update (presumably this gem and then apps that use it).

**Comment by ericfranz** [comment]
This is a great issue to fix after we move to a monorepo, because its change would currently affect multiple repos.
