### ISSUE TITLE
Unable to delete K8 session card if pod doesn't exist

### ISSUE THREAD

**Issue by treydock** [OSC/ood_core#301]
Not sure if this issue with K8 adapter or OnDemand but I have a Kubernetes session card that is in weird state and I'm unable to delete it. The pod itself does not exist so I'm not even sure why this is not showing as `Completed` in the card.

<img width="1308" alt="Screen Shot 2021-07-12 at 11 53 57 AM" src="https://user-images.githubusercontent.com/739622/125318701-18306380-e308-11eb-92e4-b6c9fddedf12.png">

**Comment by treydock** [comment]
This was with #300 in my dev environment. Now sure if that PR is the issue, since that PR didn't modify the early `Completed` return for pod with no JSON.

**Comment by johrstrom** [comment]
You're likely looking at that in a different portal.  Related to #294 - if you're logged into prod seeing a job you ran in test you won't be able to delete it from prod.

Same with `pitzer` on class osc edu.  Because class doesn't have Pitzer - OOD shows the job but doesn't know how to deal with it.

**Comment by treydock** [comment]
I think you're right, too many open tabs with same favicon so I think I ran a pod in test and it was not something I could delete on dev.  Closing this issue as I loaded by browser with dev dashboard in test environment and the card was immediately gone in all environments.
