### ISSUE TITLE
Torque adapter should support an array for native

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#65]
Right now the Torque adapter is the ood-ball for the native arguments. Every other adapter accepts an array of command line arguments, and the translation from job script headers to this array is easy to do once you understand the convention.

But with Torque, it is a hash, and for each PBS header, I have to find the corresponding key that pbs-ruby gem uses and then use that in the hash.

A simple solution would be to extend the Torque adapter to accept a Hash or an Array and respond accordingly. I'm not sure, however, if it is easy in pbs-ruby to support arbitrary command line arguments to qsub.

**Comment by nickjer** [comment]
**Off topic:**

One of my qualms with the `native:` being an array is that we can't merge arrays, although there are far more issues with using a hash instead (see #52). And I was interested in making a Slurm gem that made direct calls to the Slurm library using FFI in the future, especially since OSC may be moving to Slurm (so Slurm would have a similar interface to PBS).

**On topic:**

For the instance method in question

```
PBS::Batch#submit_script(script, queue: nil, headers: {}, resources: {}, envvars: {}, qsub: true)`
```

we would have to decompose an array of arguments into the corresponding `headers`, `resources` and `envvars` hash. I do not know off the top of my head how difficult this would be though.
