### ISSUE TITLE
Add ability to change VNC password length

### ISSUE THREAD

**Issue by Robbe7730** [OSC/ood_core#93]
Right now, the password length for `change_passwd` in `lib/ood_core/batch_connect/templates/vnc.rb` is hardcoded to be 8 characters. It would be nice to be able to change the length, possibly using the default value of `create_passwd`.

**Comment by ericfranz** [comment]
@MorganRodgers you may have seen this already but https://github.com/OSC/ood_core/blob/d21a1d62a41b1a3e6d05a28cfe1100bb931597f9/lib/ood_core/batch_connect/templates/vnc.rb#L74-L75 is the offending code and it seems like if it would fetch the value from the context and use 8 as default otherwise then it would allow batch connect apps to change the value in the submit.yml (in the batch_connect hash).

**Comment by ericfranz** [comment]
Though there definitely may be another better/preferred solution.

**Comment by Robbe7730** [comment]
#94 fixes it, closing this issue. Thanks for the help!

**Comment by ericfranz** [comment]
@Robbe7730 you are welcome! Thank you for opening the issue.
